package com.github.botn365.botdustries.loaders;

import com.github.botn365.botdustries.stuff.GT_Fluid_Extended;
import gregtech.api.objects.GT_Fluid;
import gregtech.api.util.GT_LanguageManager;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;

import java.awt.*;

public class Fluids {

    public static GT_Fluid_Extended MOLTEN_CRYOLITE = new GT_Fluid_Extended("bot.molten.cryolite","molten.autogenerated",new short[]{10,255,200});
    public static GT_Fluid_Extended ALUMINA_SOLUTION = new GT_Fluid_Extended("bot.fluid.alumina-solution","molten.autogenerated",new short[]{96,146,194});
    public static void register() {
        MOLTEN_CRYOLITE.setTemperature(1200);
        GT_LanguageManager.addStringLocalization(MOLTEN_CRYOLITE.getUnlocalizedName(), "Molten Cryolite");
        FluidRegistry.registerFluid(MOLTEN_CRYOLITE);
        GT_LanguageManager.addStringLocalization(ALUMINA_SOLUTION.getUnlocalizedName(), "Alumina Solution");
        FluidRegistry.registerFluid(ALUMINA_SOLUTION);
    }
}
