package com.github.botn365.botdustries.loaders;

import gregtech.api.enums.TextureSet;
import gregtech.api.objects.GT_Fluid;
import gregtech.api.util.GT_LanguageManager;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;

public class LoadFluids implements Runnable
{
    public static GT_Fluid sodiumTungstate = addFluid(
            "sodiumTungstate",
            "Sodium Tungstate",
        new short[]{0xc, 0xed, 0xd7,0},
        1200
    );


    @Override
    public void run()
    {
    }

    private static GT_Fluid addFluid(String aName ,String aLocalised, short[] color ,int aTemp)
    {
        GT_Fluid tFluid = new GT_Fluid(aName,"molten.autogenerated",color);
        GT_LanguageManager.addStringLocalization(tFluid.getUnlocalizedName(),aLocalised);
        tFluid.setTemperature(aTemp);
        FluidRegistry.registerFluid(tFluid);
        return tFluid;
    }

}
